### ISSUE TITLE
Doesn't build with GHC 8.2

### ISSUE THREAD

**Issue by rvl** [tippenein/countable-inflections#3]
Hi, if you relax the cabal version bounds for the `base` package then this will build and pass its tests with GHC 8.2. Cheers!

**Comment by tippenein** [comment]
Hey! thanks for this. Looks like @flip111 handled this in #4 . Looks like there's a problem with cassava flags for this version in CI, but you should be able to use it w/ GHC 8.2 now regardless. Cheers
